In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

options = webdriver.ChromeOptions()
prefs = {"download.default_directory":"/home/hunter/ws/eda/data",
         "download.prompt_for_download":False}
options.add_experimental_option("prefs", prefs)

url = "https://ecos.bok.or.kr/#/Short/ceab25"
driver = webdriver.Chrome(service=Service("../drive/chromedriver"),
                          options=options)
driver.get(url)

In [2]:
from selenium.webdriver.common.by import By
import time
area = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[1]/div[1]/div[1]""").click()
driver.implicitly_wait(3)
area1 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[3]/div[1]/div[1]""").click()
driver.implicitly_wait(3)
area2 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[3]/div[2]/div/div/div/div/div[1]""").click()
driver.implicitly_wait(3)
area3 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[3]/div[2]/div/div/div/div/div[1]/span/div/div/div[1]/button[1]""").click()
driver.implicitly_wait(3)
area3 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[3]/div[2]/div/div/div/div/div[1]/span/div/div/div[2]/div/div/button[3]""").click()

driver.implicitly_wait(3)
area2 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[1]/div[2]/div[1]/div/div[3]/div[3]""").click()

In [3]:
driver.implicitly_wait(3)
area2 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[2]/div/div/div/div/div/div[2]/div/div[1]/div[1]/div/div/div/div[5]/button""").click()

driver.implicitly_wait(3)
area2 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div[3]""").click()
driver.implicitly_wait(3)
area2 = driver.find_element(By.XPATH, """//*[@id="centerDiv"]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div/div[3]/button[2]""").click()

In [4]:
import pandas as pd # pandas module infort


debt_data = pd.read_csv("../data/예금은행 지역별 가계대출(말잔)_26165816.csv", encoding="utf-8") #데이터 가져올때 한글 코드 확인필요 "utf-8"도 많이 씀
debt_data.head()

,통계표,계정항목,지역코드,단위,변환,2003,2004,2005,2006,2007,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,전국,십억원,원자료,"253,756.9","276,326.6","305,513.9","346,222.3","363,680.9",...,"519,636.8","563,727.8","617,420.3","660,677.8","713,084.9","767,718.8","849,869.4","910,104.9","902,574.8","915,958.7"
1,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,서울,십억원,원자료,"112,558.4","121,450.3","131,912.3","144,006.8","147,815.4",...,"189,680.1","205,092.6","221,765.7","238,196.5","257,626.8","277,978.7","314,963.4","349,914.7","350,068.9","355,469.3"
2,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,부산,십억원,원자료,"16,602.4","18,382.1","19,860.8","20,779.5","21,573.2",...,"32,305.3","35,897.3","40,196.0","44,573.6","49,111.2","52,611.7","58,433.2","61,904.2","61,668.1","62,562.7"
3,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,대구,십억원,원자료,"8,825.8","9,567.4","11,197.7","13,172.1","13,848.8",...,"19,301.2","23,623.3","25,414.4","25,872.7","27,369.6","30,471.1","34,974.2","38,845.1","39,623.3","41,531.0"
4,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,인천,십억원,원자료,"13,344.1","14,025.1","15,401.1","17,793.0","19,124.6",...,"32,443.4","33,087.2","36,471.8","39,555.5","42,339.4","46,031.8","49,449.8","52,889.1","53,480.8","54,997.4"

In [89]:
debt_data

,통계표,계정항목,지역코드,단위,변환,2003,2004,2005,2006,2007,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,전국,십억원,원자료,"253,756.9","276,326.6","305,513.9","346,222.3","363,680.9",...,"519,636.8","563,727.8","617,420.3","660,677.8","713,084.9","767,718.8","849,869.4","910,104.9","902,574.8","915,958.7"
1,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,서울,십억원,원자료,"112,558.4","121,450.3","131,912.3","144,006.8","147,815.4",...,"189,680.1","205,092.6","221,765.7","238,196.5","257,626.8","277,978.7","314,963.4","349,914.7","350,068.9","355,469.3"
2,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,부산,십억원,원자료,"16,602.4","18,382.1","19,860.8","20,779.5","21,573.2",...,"32,305.3","35,897.3","40,196.0","44,573.6","49,111.2","52,611.7","58,433.2","61,904.2","61,668.1","62,562.7"
3,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,대구,십억원,원자료,"8,825.8","9,567.4","11,197.7","13,172.1","13,848.8",...,"19,301.2","23,623.3","25,414.4","25,872.7","27,369.6","30,471.1","34,974.2","38,845.1","39,623.3","41,531.0"
4,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,인천,십억원,원자료,"13,344.1","14,025.1","15,401.1","17,793.0","19,124.6",...,"32,443.4","33,087.2","36,471.8","39,555.5","42,339.4","46,031.8","49,449.8","52,889.1","53,480.8","54,997.4"
5,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,광주,십억원,원자료,"4,645.1","4,844.9","5,258.3","5,998.3","6,516.5",...,"9,342.2","10,784.5","11,840.6","12,450.3","14,401.7","16,516.7","18,648.3","20,313.1","19,938.6","20,506.7"
6,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,대전,십억원,원자료,"5,988.9","7,034.2","8,137.5","8,458.0","8,422.2",...,"12,925.3","13,429.1","14,374.9","15,160.6","16,069.5","17,358.2","19,380.7","20,020.9","18,959.4","19,149.5"
7,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,울산,십억원,원자료,"2,790.1","3,090.2","3,662.4","4,774.8","5,297.1",...,"8,530.9","9,738.2","10,824.9","11,870.7","11,922.5","12,097.2","12,778.6","13,218.3","12,763.3","12,843.2"
8,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,경기,십억원,원자료,"55,209.6","61,144.7","69,098.2","84,580.5","91,015.5",...,"137,576.7","144,441.5","158,747.5","169,610.7","184,381.2","199,528.2","218,761.3","227,468.2","222,624.7","224,765.0"
9,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,강원,십억원,원자료,"3,580.2","3,948.8","4,521.3","5,211.5","5,344.3",...,"6,430.0","6,690.6","7,292.6","8,167.8","9,213.6","10,063.8","10,595.5","10,833.4","10,765.6","10,993.9"
10,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,충북,십억원,원자료,"3,135.9","3,408.3","4,084.6","4,683.8","5,104.8",...,"7,717.1","8,632.1","9,092.0","9,362.6","10,144.0","10,573.1","10,911.1","11,242.3","10,830.4","11,284.2"
11,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,충남,십억원,원자료,"4,637.7","5,659.6","6,789.2","7,873.8","8,484.9",...,"12,923.9","14,535.5","15,469.8","15,140.5","15,428.9","15,659.5","16,916.0","17,896.6","17,783.3","18,107.4"
12,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,전북,십억원,원자료,"4,052.6","4,463.9","4,810.0","5,344.5","5,773.7",...,"8,734.8","9,136.3","9,705.7","10,354.1","10,764.1","11,395.8","12,235.1","12,119.6","11,593.3","11,172.3"
13,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,전남,십억원,원자료,"3,459.1","3,425.2","3,570.6","3,870.9","4,150.0",...,"5,840.9","6,278.1","6,805.5","7,356.4","8,110.2","9,160.8","10,697.4","11,053.4","10,390.2","9,955.7"
14,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,경북,십억원,원자료,"4,754.5","4,763.6","4,935.9","5,834.4","6,591.6",...,"9,830.2","12,016.9","13,205.7","13,667.9","13,902.4","14,626.1","15,579.2","15,486.8","15,234.1","15,800.6"
15,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,경남,십억원,원자료,"8,395.0","9,209.5","10,292.9","11,816.8","12,544.4",...,"20,599.6","22,886.8","25,815.8","26,927.3","28,156.8","28,448.8","29,356.7","30,301.4","30,730.7","30,943.8"
16,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,제주,십억원,원자료,"1,777.5","1,908.8","1,980.8","2,023.5","2,073.9",...,"2,734.5","3,920.5","5,713.1","7,163.0","8,293.0","8,859.0","9,288.6","9,520.7","9,080.8","8,761.7"
17,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),예금은행,세종,십억원,원자료,NaN,NaN,NaN,NaN,NaN,...,"2,720.7","3,537.2","4,684.3","5,247.6","5,849.8","6,338.4","6,900.3","7,076.9","7,039.3","7,114.3"
18,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,전국,십억원,원자료,NaN,NaN,NaN,"240,951.4","245,763.5",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
19,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,서울,십억원,원자료,NaN,NaN,NaN,"100,226.7","98,375.1",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
20,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,부산,십억원,원자료,NaN,NaN,NaN,"14,475.1","14,467.5",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
21,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,대구,십억원,원자료,NaN,NaN,NaN,"9,160.8","9,349.3",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
22,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,인천,십억원,원자료,NaN,NaN,NaN,"13,963.4","15,121.5",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
23,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,광주,십억원,원자료,NaN,NaN,NaN,"3,440.2","3,693.0",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
24,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,대전,십억원,원자료,NaN,NaN,NaN,"5,491.7","5,047.9",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
25,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,울산,십억원,원자료,NaN,NaN,NaN,"3,268.4","3,660.1",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
26,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,경기,십억원,원자료,NaN,NaN,NaN,"65,012.5","69,155.9",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
27,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,강원,십억원,원자료,NaN,NaN,NaN,"2,849.6","2,744.4",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
28,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,충북,십억원,원자료,NaN,NaN,NaN,"2,841.3","3,080.6",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
29,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,충남,십억원,원자료,NaN,NaN,NaN,"5,004.7","5,089.2",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
30,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,전북,십억원,원자료,NaN,NaN,NaN,"2,670.7","2,761.5",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
31,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,전남,십억원,원자료,NaN,NaN,NaN,"1,561.0","1,607.6",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
32,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,경북,십억원,원자료,NaN,NaN,NaN,"2,919.8","3,317.4",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
33,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,경남,십억원,원자료,NaN,NaN,NaN,"7,317.9","7,667.0",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
34,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,제주,십억원,원자료,NaN,NaN,NaN,747.5,625.4,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
35,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),주택담보대출-예금은행,세종,십억원,원자료,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"
36,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,전국,십억원,원자료,NaN,NaN,NaN,"105,270.9","117,917.5",...,"154,057.1","161,999.3","174,856.2","196,469.3","218,819.4","233,752.3","265,972.7","280,543.0","258,442.4","243,848.5"
37,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,서울,십억원,원자료,NaN,NaN,NaN,"43,780.1","49,440.3",...,"65,840.7","68,170.9","71,240.9","80,583.2","91,375.4","99,700.9","115,016.9","126,432.9","121,964.6","118,215.8"
38,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,부산,십억원,원자료,NaN,NaN,NaN,"6,304.4","7,105.7",...,"7,784.8","8,406.3","9,569.7","11,134.0","12,418.3","12,824.1","14,023.3","14,264.7","13,108.6","12,396.8"
39,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,대구,십억원,원자료,NaN,NaN,NaN,"4,011.3","4,499.5",...,"5,516.1","6,033.5","6,548.7","7,269.5","7,536.4","8,231.1","9,975.6","10,775.3","9,454.4","9,126.5"
40,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,인천,십억원,원자료,NaN,NaN,NaN,"3,829.6","4,003.1",...,"5,625.9","6,098.4","6,708.1","7,755.0","8,767.1","9,237.6","10,215.8","10,510.8","9,376.3","8,557.8"
41,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,광주,십억원,원자료,NaN,NaN,NaN,"2,558.1","2,823.5",...,"2,709.7","2,955.8","3,281.1","3,866.0","4,406.5","4,795.8","5,344.2","5,801.5","5,889.4","5,886.9"
42,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,대전,십억원,원자료,NaN,NaN,NaN,"2,966.3","3,374.3",...,"3,912.9","4,173.5","4,521.7","4,892.9","5,428.2","5,746.7","6,539.0","6,640.3","5,694.4","5,087.2"
43,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,울산,십억원,원자료,NaN,NaN,NaN,"1,506.4","1,636.9",...,"2,324.1","2,706.3","3,096.8","3,557.8","3,760.9","3,983.5","4,504.9","4,484.9","3,851.8","3,441.7"
44,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,경기,십억원,원자료,NaN,NaN,NaN,"19,568.0","21,859.6",...,"32,644.8","33,072.5","35,330.4","38,457.9","42,242.9","44,477.7","50,342.5","51,151.2","45,171.6","41,489.5"
45,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,강원,십억원,원자료,NaN,NaN,NaN,"2,361.9","2,599.8",...,"2,979.5","3,159.7","3,494.1","3,857.1","4,166.3","4,308.3","4,654.2","4,650.5","4,038.4","3,705.6"
46,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,충북,십억원,원자료,NaN,NaN,NaN,"1,842.5","2,024.3",...,"2,632.7","2,875.3","3,129.2","3,388.7","3,785.3","3,961.7","4,418.4","4,458.5","3,812.8","3,503.1"
47,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,충남,십억원,원자료,NaN,NaN,NaN,"2,869.1","3,395.7",...,"4,092.9","4,197.3","4,704.0","5,059.0","5,527.4","5,772.1","6,678.5","6,806.0","5,808.6","5,158.2"
48,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,전북,십억원,원자료,NaN,NaN,NaN,"2,673.8","3,012.3",...,"3,612.3","3,814.6","4,136.0","4,423.1","4,690.9","4,907.0","5,476.6","5,436.0","4,746.9","4,288.9"
49,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,전남,십억원,원자료,NaN,NaN,NaN,"2,309.9","2,542.4",...,"2,657.8","2,927.3","3,253.0","3,648.9","3,988.3","4,119.4","4,658.2","4,758.4","4,093.8","3,703.9"
50,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,경북,십억원,원자료,NaN,NaN,NaN,"2,914.6","3,274.2",...,"3,904.0","4,223.9","4,638.1","5,194.2","5,658.0","5,950.4","6,764.0","6,896.6","6,052.6","5,449.9"
51,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,경남,십억원,원자료,NaN,NaN,NaN,"4,498.9","4,877.5",...,"5,871.8","6,542.6","7,308.4","8,142.3","8,724.2","8,900.7","9,702.4","9,682.4","8,467.8","7,672.6"
52,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,제주,십억원,원자료,NaN,NaN,NaN,"1,276.0","1,448.4",...,"1,544.4","2,088.4","3,132.0","4,283.9","5,187.2","5,483.4","5,858.9","5,862.8","5,207.6","4,730.4"
53,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),기타대출-예금은행,세종,십억원,원자료,NaN,NaN,NaN,NaN,NaN,...,403.0,553.1,763.8,955.7,"1,156.0","1,352.0","1,799.2","1,930.2","1,702.9","1,433.8"

In [96]:
import numpy as np
import pandas as pd

debt_data1 = debt_data.drop(["통계표","변환"], axis=1)

In [97]:

debt_data1.set_index("계정항목")

,지역코드,단위,2003,2004,2005,2006,2007,2008,2009,2010,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
계정항목,,,,,,,,,,,,,,,,,,,,,
예금은행,전국,십억원,"253,756.9","276,326.6","305,513.9","346,222.3","363,680.9","388,573.2","409,504.0","431,457.2",...,"519,636.8","563,727.8","617,420.3","660,677.8","713,084.9","767,718.8","849,869.4","910,104.9","902,574.8","915,958.7"
예금은행,서울,십억원,"112,558.4","121,450.3","131,912.3","144,006.8","147,815.4","157,669.7","162,208.0","169,397.2",...,"189,680.1","205,092.6","221,765.7","238,196.5","257,626.8","277,978.7","314,963.4","349,914.7","350,068.9","355,469.3"
예금은행,부산,십억원,"16,602.4","18,382.1","19,860.8","20,779.5","21,573.2","22,253.2","22,595.6","24,025.3",...,"32,305.3","35,897.3","40,196.0","44,573.6","49,111.2","52,611.7","58,433.2","61,904.2","61,668.1","62,562.7"
예금은행,대구,십억원,"8,825.8","9,567.4","11,197.7","13,172.1","13,848.8","13,730.4","13,660.7","13,674.5",...,"19,301.2","23,623.3","25,414.4","25,872.7","27,369.6","30,471.1","34,974.2","38,845.1","39,623.3","41,531.0"
예금은행,인천,십억원,"13,344.1","14,025.1","15,401.1","17,793.0","19,124.6","20,840.5","24,270.8","27,938.8",...,"32,443.4","33,087.2","36,471.8","39,555.5","42,339.4","46,031.8","49,449.8","52,889.1","53,480.8","54,997.4"
예금은행,광주,십억원,"4,645.1","4,844.9","5,258.3","5,998.3","6,516.5","6,936.3","6,694.8","6,817.7",...,"9,342.2","10,784.5","11,840.6","12,450.3","14,401.7","16,516.7","18,648.3","20,313.1","19,938.6","20,506.7"
예금은행,대전,십억원,"5,988.9","7,034.2","8,137.5","8,458.0","8,422.2","8,666.4","9,010.6","9,694.4",...,"12,925.3","13,429.1","14,374.9","15,160.6","16,069.5","17,358.2","19,380.7","20,020.9","18,959.4","19,149.5"
예금은행,울산,십억원,"2,790.1","3,090.2","3,662.4","4,774.8","5,297.1","5,779.9","5,855.3","5,676.7",...,"8,530.9","9,738.2","10,824.9","11,870.7","11,922.5","12,097.2","12,778.6","13,218.3","12,763.3","12,843.2"
예금은행,경기,십억원,"55,209.6","61,144.7","69,098.2","84,580.5","91,015.5","100,276.2","112,504.8","120,057.7",...,"137,576.7","144,441.5","158,747.5","169,610.7","184,381.2","199,528.2","218,761.3","227,468.2","222,624.7","224,765.0"
예금은행,강원,십억원,"3,580.2","3,948.8","4,521.3","5,211.5","5,344.3","5,301.7","5,194.5","5,311.7",...,"6,430.0","6,690.6","7,292.6","8,167.8","9,213.6","10,063.8","10,595.5","10,833.4","10,765.6","10,993.9"
예금은행,충북,십억원,"3,135.9","3,408.3","4,084.6","4,683.8","5,104.8","5,470.4","5,681.0","5,720.5",...,"7,717.1","8,632.1","9,092.0","9,362.6","10,144.0","10,573.1","10,911.1","11,242.3","10,830.4","11,284.2"
예금은행,충남,십억원,"4,637.7","5,659.6","6,789.2","7,873.8","8,484.9","9,651.7","10,406.8","10,801.9",...,"12,923.9","14,535.5","15,469.8","15,140.5","15,428.9","15,659.5","16,916.0","17,896.6","17,783.3","18,107.4"
예금은행,전북,십억원,"4,052.6","4,463.9","4,810.0","5,344.5","5,773.7","6,062.6","6,133.0","6,551.8",...,"8,734.8","9,136.3","9,705.7","10,354.1","10,764.1","11,395.8","12,235.1","12,119.6","11,593.3","11,172.3"
예금은행,전남,십억원,"3,459.1","3,425.2","3,570.6","3,870.9","4,150.0","4,131.8","4,146.3","4,243.3",...,"5,840.9","6,278.1","6,805.5","7,356.4","8,110.2","9,160.8","10,697.4","11,053.4","10,390.2","9,955.7"
예금은행,경북,십억원,"4,754.5","4,763.6","4,935.9","5,834.4","6,591.6","7,036.2","6,871.9","6,961.9",...,"9,830.2","12,016.9","13,205.7","13,667.9","13,902.4","14,626.1","15,579.2","15,486.8","15,234.1","15,800.6"
예금은행,경남,십억원,"8,395.0","9,209.5","10,292.9","11,816.8","12,544.4","12,706.8","12,243.0","12,522.1",...,"20,599.6","22,886.8","25,815.8","26,927.3","28,156.8","28,448.8","29,356.7","30,301.4","30,730.7","30,943.8"
예금은행,제주,십억원,"1,777.5","1,908.8","1,980.8","2,023.5","2,073.9","2,059.5","2,026.7","2,061.7",...,"2,734.5","3,920.5","5,713.1","7,163.0","8,293.0","8,859.0","9,288.6","9,520.7","9,080.8","8,761.7"
예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,720.7","3,537.2","4,684.3","5,247.6","5,849.8","6,338.4","6,900.3","7,076.9","7,039.3","7,114.3"
주택담보대출-예금은행,전국,십억원,NaN,NaN,NaN,"240,951.4","245,763.5","254,735.7","273,687.0","289,623.0",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
주택담보대출-예금은행,서울,십억원,NaN,NaN,NaN,"100,226.7","98,375.1","100,188.8","104,954.8","109,489.9",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
주택담보대출-예금은행,부산,십억원,NaN,NaN,NaN,"14,475.1","14,467.5","14,525.9","15,000.1","16,333.4",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
주택담보대출-예금은행,대구,십억원,NaN,NaN,NaN,"9,160.8","9,349.3","8,847.3","8,705.6","8,450.9",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
주택담보대출-예금은행,인천,십억원,NaN,NaN,NaN,"13,963.4","15,121.5","16,134.6","19,243.9","22,601.9",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
주택담보대출-예금은행,광주,십억원,NaN,NaN,NaN,"3,440.2","3,693.0","3,997.8","3,846.2","3,987.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
주택담보대출-예금은행,대전,십억원,NaN,NaN,NaN,"5,491.7","5,047.9","4,930.0","5,301.1","5,942.9",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
주택담보대출-예금은행,울산,십억원,NaN,NaN,NaN,"3,268.4","3,660.1","3,942.1","3,960.9","3,731.7",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
주택담보대출-예금은행,경기,십억원,NaN,NaN,NaN,"65,012.5","69,155.9","74,606.6","85,288.6","91,020.6",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
주택담보대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,849.6","2,744.4","2,557.8","2,353.9","2,386.4",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
주택담보대출-예금은행,충북,십억원,NaN,NaN,NaN,"2,841.3","3,080.6","3,298.4","3,463.4","3,441.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
주택담보대출-예금은행,충남,십억원,NaN,NaN,NaN,"5,004.7","5,089.2","5,830.5","6,416.1","6,567.2",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
주택담보대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,670.7","2,761.5","2,780.8","2,805.9","3,037.2",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
주택담보대출-예금은행,전남,십억원,NaN,NaN,NaN,"1,561.0","1,607.6","1,430.8","1,434.3","1,544.4",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
주택담보대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,919.8","3,317.4","3,494.7","3,217.6","3,192.2",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
주택담보대출-예금은행,경남,십억원,NaN,NaN,NaN,"7,317.9","7,667.0","7,621.8","7,150.9","7,315.3",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
주택담보대출-예금은행,제주,십억원,NaN,NaN,NaN,747.5,625.4,547.7,543.6,580.4,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
주택담보대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"
기타대출-예금은행,전국,십억원,NaN,NaN,NaN,"105,270.9","117,917.5","133,837.4","135,817.0","141,834.2",...,"154,057.1","161,999.3","174,856.2","196,469.3","218,819.4","233,752.3","265,972.7","280,543.0","258,442.4","243,848.5"
기타대출-예금은행,서울,십억원,NaN,NaN,NaN,"43,780.1","49,440.3","57,480.8","57,253.2","59,907.2",...,"65,840.7","68,170.9","71,240.9","80,583.2","91,375.4","99,700.9","115,016.9","126,432.9","121,964.6","118,215.8"
기타대출-예금은행,부산,십억원,NaN,NaN,NaN,"6,304.4","7,105.7","7,727.3","7,595.4","7,691.8",...,"7,784.8","8,406.3","9,569.7","11,134.0","12,418.3","12,824.1","14,023.3","14,264.7","13,108.6","12,396.8"
기타대출-예금은행,대구,십억원,NaN,NaN,NaN,"4,011.3","4,499.5","4,883.1","4,955.1","5,223.6",...,"5,516.1","6,033.5","6,548.7","7,269.5","7,536.4","8,231.1","9,975.6","10,775.3","9,454.4","9,126.5"
기타대출-예금은행,인천,십억원,NaN,NaN,NaN,"3,829.6","4,003.1","4,705.9","5,027.0","5,336.9",...,"5,625.9","6,098.4","6,708.1","7,755.0","8,767.1","9,237.6","10,215.8","10,510.8","9,376.3","8,557.8"
기타대출-예금은행,광주,십억원,NaN,NaN,NaN,"2,558.1","2,823.5","2,938.5","2,848.6","2,830.5",...,"2,709.7","2,955.8","3,281.1","3,866.0","4,406.5","4,795.8","5,344.2","5,801.5","5,889.4","5,886.9"
기타대출-예금은행,대전,십억원,NaN,NaN,NaN,"2,966.3","3,374.3","3,736.4","3,709.5","3,751.5",...,"3,912.9","4,173.5","4,521.7","4,892.9","5,428.2","5,746.7","6,539.0","6,640.3","5,694.4","5,087.2"
기타대출-예금은행,울산,십억원,NaN,NaN,NaN,"1,506.4","1,636.9","1,837.8","1,894.5","1,945.0",...,"2,324.1","2,706.3","3,096.8","3,557.8","3,760.9","3,983.5","4,504.9","4,484.9","3,851.8","3,441.7"
기타대출-예금은행,경기,십억원,NaN,NaN,NaN,"19,568.0","21,859.6","25,669.5","27,216.3","29,037.1",...,"32,644.8","33,072.5","35,330.4","38,457.9","42,242.9","44,477.7","50,342.5","51,151.2","45,171.6","41,489.5"
기타대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,361.9","2,599.8","2,743.9","2,840.6","2,925.4",...,"2,979.5","3,159.7","3,494.1","3,857.1","4,166.3","4,308.3","4,654.2","4,650.5","4,038.4","3,705.6"
기타대출-예금은행,충북,십억원,NaN,NaN,NaN,"1,842.5","2,024.3","2,172.0","2,217.6","2,279.1",...,"2,632.7","2,875.3","3,129.2","3,388.7","3,785.3","3,961.7","4,418.4","4,458.5","3,812.8","3,503.1"
기타대출-예금은행,충남,십억원,NaN,NaN,NaN,"2,869.1","3,395.7","3,821.2","3,990.7","4,234.7",...,"4,092.9","4,197.3","4,704.0","5,059.0","5,527.4","5,772.1","6,678.5","6,806.0","5,808.6","5,158.2"
기타대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,673.8","3,012.3","3,281.8","3,327.1","3,514.6",...,"3,612.3","3,814.6","4,136.0","4,423.1","4,690.9","4,907.0","5,476.6","5,436.0","4,746.9","4,288.9"
기타대출-예금은행,전남,십억원,NaN,NaN,NaN,"2,309.9","2,542.4","2,701.0","2,712.1","2,698.9",...,"2,657.8","2,927.3","3,253.0","3,648.9","3,988.3","4,119.4","4,658.2","4,758.4","4,093.8","3,703.9"
기타대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,914.6","3,274.2","3,541.5","3,654.3","3,769.7",...,"3,904.0","4,223.9","4,638.1","5,194.2","5,658.0","5,950.4","6,764.0","6,896.6","6,052.6","5,449.9"
기타대출-예금은행,경남,십억원,NaN,NaN,NaN,"4,498.9","4,877.5","5,085.0","5,092.1","5,206.8",...,"5,871.8","6,542.6","7,308.4","8,142.3","8,724.2","8,900.7","9,702.4","9,682.4","8,467.8","7,672.6"
기타대출-예금은행,제주,십억원,NaN,NaN,NaN,"1,276.0","1,448.4","1,511.7","1,483.1","1,481.3",...,"1,544.4","2,088.4","3,132.0","4,283.9","5,187.2","5,483.4","5,858.9","5,862.8","5,207.6","4,730.4"
기타대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,403.0,553.1,763.8,955.7,"1,156.0","1,352.0","1,799.2","1,930.2","1,702.9","1,433.8"

In [98]:
debt_data1 = pd.DataFrame(debt_data1).set_index('계정항목')
debt_data1= debt_data1.drop('예금은행')

In [108]:
debt_data1

,지역코드,단위,2003,2004,2005,2006,2007,2008,2009,2010,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
계정항목,,,,,,,,,,,,,,,,,,,,,
주택담보대출-예금은행,전국,십억원,NaN,NaN,NaN,"240,951.4","245,763.5","254,735.7","273,687.0","289,623.0",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
주택담보대출-예금은행,서울,십억원,NaN,NaN,NaN,"100,226.7","98,375.1","100,188.8","104,954.8","109,489.9",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
주택담보대출-예금은행,부산,십억원,NaN,NaN,NaN,"14,475.1","14,467.5","14,525.9","15,000.1","16,333.4",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
주택담보대출-예금은행,대구,십억원,NaN,NaN,NaN,"9,160.8","9,349.3","8,847.3","8,705.6","8,450.9",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
주택담보대출-예금은행,인천,십억원,NaN,NaN,NaN,"13,963.4","15,121.5","16,134.6","19,243.9","22,601.9",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
주택담보대출-예금은행,광주,십억원,NaN,NaN,NaN,"3,440.2","3,693.0","3,997.8","3,846.2","3,987.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
주택담보대출-예금은행,대전,십억원,NaN,NaN,NaN,"5,491.7","5,047.9","4,930.0","5,301.1","5,942.9",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
주택담보대출-예금은행,울산,십억원,NaN,NaN,NaN,"3,268.4","3,660.1","3,942.1","3,960.9","3,731.7",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
주택담보대출-예금은행,경기,십억원,NaN,NaN,NaN,"65,012.5","69,155.9","74,606.6","85,288.6","91,020.6",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
주택담보대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,849.6","2,744.4","2,557.8","2,353.9","2,386.4",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
주택담보대출-예금은행,충북,십억원,NaN,NaN,NaN,"2,841.3","3,080.6","3,298.4","3,463.4","3,441.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
주택담보대출-예금은행,충남,십억원,NaN,NaN,NaN,"5,004.7","5,089.2","5,830.5","6,416.1","6,567.2",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
주택담보대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,670.7","2,761.5","2,780.8","2,805.9","3,037.2",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
주택담보대출-예금은행,전남,십억원,NaN,NaN,NaN,"1,561.0","1,607.6","1,430.8","1,434.3","1,544.4",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
주택담보대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,919.8","3,317.4","3,494.7","3,217.6","3,192.2",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
주택담보대출-예금은행,경남,십억원,NaN,NaN,NaN,"7,317.9","7,667.0","7,621.8","7,150.9","7,315.3",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
주택담보대출-예금은행,제주,십억원,NaN,NaN,NaN,747.5,625.4,547.7,543.6,580.4,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
주택담보대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"
기타대출-예금은행,전국,십억원,NaN,NaN,NaN,"105,270.9","117,917.5","133,837.4","135,817.0","141,834.2",...,"154,057.1","161,999.3","174,856.2","196,469.3","218,819.4","233,752.3","265,972.7","280,543.0","258,442.4","243,848.5"
기타대출-예금은행,서울,십억원,NaN,NaN,NaN,"43,780.1","49,440.3","57,480.8","57,253.2","59,907.2",...,"65,840.7","68,170.9","71,240.9","80,583.2","91,375.4","99,700.9","115,016.9","126,432.9","121,964.6","118,215.8"
기타대출-예금은행,부산,십억원,NaN,NaN,NaN,"6,304.4","7,105.7","7,727.3","7,595.4","7,691.8",...,"7,784.8","8,406.3","9,569.7","11,134.0","12,418.3","12,824.1","14,023.3","14,264.7","13,108.6","12,396.8"
기타대출-예금은행,대구,십억원,NaN,NaN,NaN,"4,011.3","4,499.5","4,883.1","4,955.1","5,223.6",...,"5,516.1","6,033.5","6,548.7","7,269.5","7,536.4","8,231.1","9,975.6","10,775.3","9,454.4","9,126.5"
기타대출-예금은행,인천,십억원,NaN,NaN,NaN,"3,829.6","4,003.1","4,705.9","5,027.0","5,336.9",...,"5,625.9","6,098.4","6,708.1","7,755.0","8,767.1","9,237.6","10,215.8","10,510.8","9,376.3","8,557.8"
기타대출-예금은행,광주,십억원,NaN,NaN,NaN,"2,558.1","2,823.5","2,938.5","2,848.6","2,830.5",...,"2,709.7","2,955.8","3,281.1","3,866.0","4,406.5","4,795.8","5,344.2","5,801.5","5,889.4","5,886.9"
기타대출-예금은행,대전,십억원,NaN,NaN,NaN,"2,966.3","3,374.3","3,736.4","3,709.5","3,751.5",...,"3,912.9","4,173.5","4,521.7","4,892.9","5,428.2","5,746.7","6,539.0","6,640.3","5,694.4","5,087.2"
기타대출-예금은행,울산,십억원,NaN,NaN,NaN,"1,506.4","1,636.9","1,837.8","1,894.5","1,945.0",...,"2,324.1","2,706.3","3,096.8","3,557.8","3,760.9","3,983.5","4,504.9","4,484.9","3,851.8","3,441.7"
기타대출-예금은행,경기,십억원,NaN,NaN,NaN,"19,568.0","21,859.6","25,669.5","27,216.3","29,037.1",...,"32,644.8","33,072.5","35,330.4","38,457.9","42,242.9","44,477.7","50,342.5","51,151.2","45,171.6","41,489.5"
기타대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,361.9","2,599.8","2,743.9","2,840.6","2,925.4",...,"2,979.5","3,159.7","3,494.1","3,857.1","4,166.3","4,308.3","4,654.2","4,650.5","4,038.4","3,705.6"
기타대출-예금은행,충북,십억원,NaN,NaN,NaN,"1,842.5","2,024.3","2,172.0","2,217.6","2,279.1",...,"2,632.7","2,875.3","3,129.2","3,388.7","3,785.3","3,961.7","4,418.4","4,458.5","3,812.8","3,503.1"
기타대출-예금은행,충남,십억원,NaN,NaN,NaN,"2,869.1","3,395.7","3,821.2","3,990.7","4,234.7",...,"4,092.9","4,197.3","4,704.0","5,059.0","5,527.4","5,772.1","6,678.5","6,806.0","5,808.6","5,158.2"
기타대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,673.8","3,012.3","3,281.8","3,327.1","3,514.6",...,"3,612.3","3,814.6","4,136.0","4,423.1","4,690.9","4,907.0","5,476.6","5,436.0","4,746.9","4,288.9"
기타대출-예금은행,전남,십억원,NaN,NaN,NaN,"2,309.9","2,542.4","2,701.0","2,712.1","2,698.9",...,"2,657.8","2,927.3","3,253.0","3,648.9","3,988.3","4,119.4","4,658.2","4,758.4","4,093.8","3,703.9"
기타대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,914.6","3,274.2","3,541.5","3,654.3","3,769.7",...,"3,904.0","4,223.9","4,638.1","5,194.2","5,658.0","5,950.4","6,764.0","6,896.6","6,052.6","5,449.9"
기타대출-예금은행,경남,십억원,NaN,NaN,NaN,"4,498.9","4,877.5","5,085.0","5,092.1","5,206.8",...,"5,871.8","6,542.6","7,308.4","8,142.3","8,724.2","8,900.7","9,702.4","9,682.4","8,467.8","7,672.6"
기타대출-예금은행,제주,십억원,NaN,NaN,NaN,"1,276.0","1,448.4","1,511.7","1,483.1","1,481.3",...,"1,544.4","2,088.4","3,132.0","4,283.9","5,187.2","5,483.4","5,858.9","5,862.8","5,207.6","4,730.4"
기타대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,403.0,553.1,763.8,955.7,"1,156.0","1,352.0","1,799.2","1,930.2","1,702.9","1,433.8"

In [148]:
df = debt_data1.reset_index()

In [149]:
df

,계정항목,지역코드,단위,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,주택담보대출-예금은행,전국,십억원,NaN,NaN,NaN,"240,951.4","245,763.5","254,735.7","273,687.0",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
1,주택담보대출-예금은행,서울,십억원,NaN,NaN,NaN,"100,226.7","98,375.1","100,188.8","104,954.8",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
2,주택담보대출-예금은행,부산,십억원,NaN,NaN,NaN,"14,475.1","14,467.5","14,525.9","15,000.1",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
3,주택담보대출-예금은행,대구,십억원,NaN,NaN,NaN,"9,160.8","9,349.3","8,847.3","8,705.6",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
4,주택담보대출-예금은행,인천,십억원,NaN,NaN,NaN,"13,963.4","15,121.5","16,134.6","19,243.9",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
5,주택담보대출-예금은행,광주,십억원,NaN,NaN,NaN,"3,440.2","3,693.0","3,997.8","3,846.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
6,주택담보대출-예금은행,대전,십억원,NaN,NaN,NaN,"5,491.7","5,047.9","4,930.0","5,301.1",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
7,주택담보대출-예금은행,울산,십억원,NaN,NaN,NaN,"3,268.4","3,660.1","3,942.1","3,960.9",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
8,주택담보대출-예금은행,경기,십억원,NaN,NaN,NaN,"65,012.5","69,155.9","74,606.6","85,288.6",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
9,주택담보대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,849.6","2,744.4","2,557.8","2,353.9",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
10,주택담보대출-예금은행,충북,십억원,NaN,NaN,NaN,"2,841.3","3,080.6","3,298.4","3,463.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
11,주택담보대출-예금은행,충남,십억원,NaN,NaN,NaN,"5,004.7","5,089.2","5,830.5","6,416.1",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
12,주택담보대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,670.7","2,761.5","2,780.8","2,805.9",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
13,주택담보대출-예금은행,전남,십억원,NaN,NaN,NaN,"1,561.0","1,607.6","1,430.8","1,434.3",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
14,주택담보대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,919.8","3,317.4","3,494.7","3,217.6",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
15,주택담보대출-예금은행,경남,십억원,NaN,NaN,NaN,"7,317.9","7,667.0","7,621.8","7,150.9",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
16,주택담보대출-예금은행,제주,십억원,NaN,NaN,NaN,747.5,625.4,547.7,543.6,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
17,주택담보대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"
18,기타대출-예금은행,전국,십억원,NaN,NaN,NaN,"105,270.9","117,917.5","133,837.4","135,817.0",...,"154,057.1","161,999.3","174,856.2","196,469.3","218,819.4","233,752.3","265,972.7","280,543.0","258,442.4","243,848.5"
19,기타대출-예금은행,서울,십억원,NaN,NaN,NaN,"43,780.1","49,440.3","57,480.8","57,253.2",...,"65,840.7","68,170.9","71,240.9","80,583.2","91,375.4","99,700.9","115,016.9","126,432.9","121,964.6","118,215.8"
20,기타대출-예금은행,부산,십억원,NaN,NaN,NaN,"6,304.4","7,105.7","7,727.3","7,595.4",...,"7,784.8","8,406.3","9,569.7","11,134.0","12,418.3","12,824.1","14,023.3","14,264.7","13,108.6","12,396.8"
21,기타대출-예금은행,대구,십억원,NaN,NaN,NaN,"4,011.3","4,499.5","4,883.1","4,955.1",...,"5,516.1","6,033.5","6,548.7","7,269.5","7,536.4","8,231.1","9,975.6","10,775.3","9,454.4","9,126.5"
22,기타대출-예금은행,인천,십억원,NaN,NaN,NaN,"3,829.6","4,003.1","4,705.9","5,027.0",...,"5,625.9","6,098.4","6,708.1","7,755.0","8,767.1","9,237.6","10,215.8","10,510.8","9,376.3","8,557.8"
23,기타대출-예금은행,광주,십억원,NaN,NaN,NaN,"2,558.1","2,823.5","2,938.5","2,848.6",...,"2,709.7","2,955.8","3,281.1","3,866.0","4,406.5","4,795.8","5,344.2","5,801.5","5,889.4","5,886.9"
24,기타대출-예금은행,대전,십억원,NaN,NaN,NaN,"2,966.3","3,374.3","3,736.4","3,709.5",...,"3,912.9","4,173.5","4,521.7","4,892.9","5,428.2","5,746.7","6,539.0","6,640.3","5,694.4","5,087.2"
25,기타대출-예금은행,울산,십억원,NaN,NaN,NaN,"1,506.4","1,636.9","1,837.8","1,894.5",...,"2,324.1","2,706.3","3,096.8","3,557.8","3,760.9","3,983.5","4,504.9","4,484.9","3,851.8","3,441.7"
26,기타대출-예금은행,경기,십억원,NaN,NaN,NaN,"19,568.0","21,859.6","25,669.5","27,216.3",...,"32,644.8","33,072.5","35,330.4","38,457.9","42,242.9","44,477.7","50,342.5","51,151.2","45,171.6","41,489.5"
27,기타대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,361.9","2,599.8","2,743.9","2,840.6",...,"2,979.5","3,159.7","3,494.1","3,857.1","4,166.3","4,308.3","4,654.2","4,650.5","4,038.4","3,705.6"
28,기타대출-예금은행,충북,십억원,NaN,NaN,NaN,"1,842.5","2,024.3","2,172.0","2,217.6",...,"2,632.7","2,875.3","3,129.2","3,388.7","3,785.3","3,961.7","4,418.4","4,458.5","3,812.8","3,503.1"
29,기타대출-예금은행,충남,십억원,NaN,NaN,NaN,"2,869.1","3,395.7","3,821.2","3,990.7",...,"4,092.9","4,197.3","4,704.0","5,059.0","5,527.4","5,772.1","6,678.5","6,806.0","5,808.6","5,158.2"
30,기타대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,673.8","3,012.3","3,281.8","3,327.1",...,"3,612.3","3,814.6","4,136.0","4,423.1","4,690.9","4,907.0","5,476.6","5,436.0","4,746.9","4,288.9"
31,기타대출-예금은행,전남,십억원,NaN,NaN,NaN,"2,309.9","2,542.4","2,701.0","2,712.1",...,"2,657.8","2,927.3","3,253.0","3,648.9","3,988.3","4,119.4","4,658.2","4,758.4","4,093.8","3,703.9"
32,기타대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,914.6","3,274.2","3,541.5","3,654.3",...,"3,904.0","4,223.9","4,638.1","5,194.2","5,658.0","5,950.4","6,764.0","6,896.6","6,052.6","5,449.9"
33,기타대출-예금은행,경남,십억원,NaN,NaN,NaN,"4,498.9","4,877.5","5,085.0","5,092.1",...,"5,871.8","6,542.6","7,308.4","8,142.3","8,724.2","8,900.7","9,702.4","9,682.4","8,467.8","7,672.6"
34,기타대출-예금은행,제주,십억원,NaN,NaN,NaN,"1,276.0","1,448.4","1,511.7","1,483.1",...,"1,544.4","2,088.4","3,132.0","4,283.9","5,187.2","5,483.4","5,858.9","5,862.8","5,207.6","4,730.4"
35,기타대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,403.0,553.1,763.8,955.7,"1,156.0","1,352.0","1,799.2","1,930.2","1,702.9","1,433.8"

In [150]:
df = df.iloc[:18]

In [151]:
df

,계정항목,지역코드,단위,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,주택담보대출-예금은행,전국,십억원,NaN,NaN,NaN,"240,951.4","245,763.5","254,735.7","273,687.0",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
1,주택담보대출-예금은행,서울,십억원,NaN,NaN,NaN,"100,226.7","98,375.1","100,188.8","104,954.8",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
2,주택담보대출-예금은행,부산,십억원,NaN,NaN,NaN,"14,475.1","14,467.5","14,525.9","15,000.1",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
3,주택담보대출-예금은행,대구,십억원,NaN,NaN,NaN,"9,160.8","9,349.3","8,847.3","8,705.6",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
4,주택담보대출-예금은행,인천,십억원,NaN,NaN,NaN,"13,963.4","15,121.5","16,134.6","19,243.9",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
5,주택담보대출-예금은행,광주,십억원,NaN,NaN,NaN,"3,440.2","3,693.0","3,997.8","3,846.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
6,주택담보대출-예금은행,대전,십억원,NaN,NaN,NaN,"5,491.7","5,047.9","4,930.0","5,301.1",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
7,주택담보대출-예금은행,울산,십억원,NaN,NaN,NaN,"3,268.4","3,660.1","3,942.1","3,960.9",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
8,주택담보대출-예금은행,경기,십억원,NaN,NaN,NaN,"65,012.5","69,155.9","74,606.6","85,288.6",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
9,주택담보대출-예금은행,강원,십억원,NaN,NaN,NaN,"2,849.6","2,744.4","2,557.8","2,353.9",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
10,주택담보대출-예금은행,충북,십억원,NaN,NaN,NaN,"2,841.3","3,080.6","3,298.4","3,463.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
11,주택담보대출-예금은행,충남,십억원,NaN,NaN,NaN,"5,004.7","5,089.2","5,830.5","6,416.1",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
12,주택담보대출-예금은행,전북,십억원,NaN,NaN,NaN,"2,670.7","2,761.5","2,780.8","2,805.9",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
13,주택담보대출-예금은행,전남,십억원,NaN,NaN,NaN,"1,561.0","1,607.6","1,430.8","1,434.3",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
14,주택담보대출-예금은행,경북,십억원,NaN,NaN,NaN,"2,919.8","3,317.4","3,494.7","3,217.6",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
15,주택담보대출-예금은행,경남,십억원,NaN,NaN,NaN,"7,317.9","7,667.0","7,621.8","7,150.9",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
16,주택담보대출-예금은행,제주,십억원,NaN,NaN,NaN,747.5,625.4,547.7,543.6,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
17,주택담보대출-예금은행,세종,십억원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"

In [152]:
df.fillna(0)

/tmp/ipykernel_17812/516507702.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0)

,계정항목,지역코드,단위,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,주택담보대출-예금은행,전국,십억원,0,0,0,"240,951.4","245,763.5","254,735.7","273,687.0",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
1,주택담보대출-예금은행,서울,십억원,0,0,0,"100,226.7","98,375.1","100,188.8","104,954.8",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
2,주택담보대출-예금은행,부산,십억원,0,0,0,"14,475.1","14,467.5","14,525.9","15,000.1",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
3,주택담보대출-예금은행,대구,십억원,0,0,0,"9,160.8","9,349.3","8,847.3","8,705.6",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
4,주택담보대출-예금은행,인천,십억원,0,0,0,"13,963.4","15,121.5","16,134.6","19,243.9",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
5,주택담보대출-예금은행,광주,십억원,0,0,0,"3,440.2","3,693.0","3,997.8","3,846.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
6,주택담보대출-예금은행,대전,십억원,0,0,0,"5,491.7","5,047.9","4,930.0","5,301.1",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
7,주택담보대출-예금은행,울산,십억원,0,0,0,"3,268.4","3,660.1","3,942.1","3,960.9",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
8,주택담보대출-예금은행,경기,십억원,0,0,0,"65,012.5","69,155.9","74,606.6","85,288.6",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
9,주택담보대출-예금은행,강원,십억원,0,0,0,"2,849.6","2,744.4","2,557.8","2,353.9",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
10,주택담보대출-예금은행,충북,십억원,0,0,0,"2,841.3","3,080.6","3,298.4","3,463.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
11,주택담보대출-예금은행,충남,십억원,0,0,0,"5,004.7","5,089.2","5,830.5","6,416.1",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
12,주택담보대출-예금은행,전북,십억원,0,0,0,"2,670.7","2,761.5","2,780.8","2,805.9",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
13,주택담보대출-예금은행,전남,십억원,0,0,0,"1,561.0","1,607.6","1,430.8","1,434.3",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
14,주택담보대출-예금은행,경북,십억원,0,0,0,"2,919.8","3,317.4","3,494.7","3,217.6",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
15,주택담보대출-예금은행,경남,십억원,0,0,0,"7,317.9","7,667.0","7,621.8","7,150.9",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
16,주택담보대출-예금은행,제주,십억원,0,0,0,747.5,625.4,547.7,543.6,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
17,주택담보대출-예금은행,세종,십억원,0,0,0,0,0,0,0,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"

In [153]:
debt_final = df.drop(['계정항목', '단위'], axis =1)

In [154]:
debt_final

,지역코드,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,전국,NaN,NaN,NaN,"240,951.4","245,763.5","254,735.7","273,687.0","289,623.0","308,876.5",...,"365,579.6","401,728.5","442,564.1","464,208.5","494,265.4","533,966.4","583,896.8","629,561.9","644,132.4","672,110.2"
1,서울,NaN,NaN,NaN,"100,226.7","98,375.1","100,188.8","104,954.8","109,489.9","113,511.0",...,"123,839.5","136,921.7","150,524.8","157,613.3","166,251.4","178,277.8","199,946.5","223,481.8","228,104.3","237,253.5"
2,부산,NaN,NaN,NaN,"14,475.1","14,467.5","14,525.9","15,000.1","16,333.4","18,469.5",...,"24,520.5","27,491.0","30,626.3","33,439.5","36,692.8","39,787.6","44,409.9","47,639.6","48,559.5","50,165.9"
3,대구,NaN,NaN,NaN,"9,160.8","9,349.3","8,847.3","8,705.6","8,450.9","8,879.6",...,"13,785.1","17,589.8","18,865.8","18,603.1","19,833.2","22,240.0","24,998.6","28,069.8","30,169.0","32,404.5"
4,인천,NaN,NaN,NaN,"13,963.4","15,121.5","16,134.6","19,243.9","22,601.9","25,396.5",...,"26,817.6","26,988.8","29,763.7","31,800.6","33,572.3","36,794.2","39,234.0","42,378.3","44,104.5","46,439.6"
5,광주,NaN,NaN,NaN,"3,440.2","3,693.0","3,997.8","3,846.2","3,987.2","4,657.2",...,"6,632.5","7,828.7","8,559.4","8,584.3","9,995.1","11,720.9","13,304.1","14,511.6","14,049.1","14,619.8"
6,대전,NaN,NaN,NaN,"5,491.7","5,047.9","4,930.0","5,301.1","5,942.9","7,139.1",...,"9,012.3","9,255.6","9,853.2","10,267.7","10,641.3","11,611.5","12,841.7","13,380.7","13,265.0","14,062.2"
7,울산,NaN,NaN,NaN,"3,268.4","3,660.1","3,942.1","3,960.9","3,731.7","4,053.5",...,"6,206.8","7,032.0","7,728.0","8,312.9","8,161.5","8,113.7","8,273.7","8,733.4","8,911.5","9,401.5"
8,경기,NaN,NaN,NaN,"65,012.5","69,155.9","74,606.6","85,288.6","91,020.6","95,453.7",...,"104,932.0","111,369.0","123,417.0","131,152.8","142,138.3","155,050.5","168,418.9","176,317.0","177,453.1","183,275.5"
9,강원,NaN,NaN,NaN,"2,849.6","2,744.4","2,557.8","2,353.9","2,386.4","2,544.9",...,"3,450.5","3,530.9","3,798.5","4,310.7","5,047.4","5,755.5","5,941.2","6,182.9","6,727.2","7,288.3"
10,충북,NaN,NaN,NaN,"2,841.3","3,080.6","3,298.4","3,463.4","3,441.4","3,679.4",...,"5,084.4","5,756.7","5,962.8","5,973.9","6,358.7","6,611.4","6,492.7","6,783.8","7,017.6","7,781.1"
11,충남,NaN,NaN,NaN,"5,004.7","5,089.2","5,830.5","6,416.1","6,567.2","6,887.4",...,"8,831.0","10,338.3","10,765.8","10,081.6","9,901.5","9,887.4","10,237.5","11,090.6","11,974.7","12,949.2"
12,전북,NaN,NaN,NaN,"2,670.7","2,761.5","2,780.8","2,805.9","3,037.2","3,496.4",...,"5,122.6","5,321.7","5,569.8","5,931.0","6,073.3","6,488.8","6,758.5","6,683.6","6,846.4","6,883.4"
13,전남,NaN,NaN,NaN,"1,561.0","1,607.6","1,430.8","1,434.3","1,544.4","1,912.7",...,"3,183.1","3,350.9","3,552.4","3,707.5","4,122.0","5,041.3","6,039.1","6,294.9","6,296.4","6,251.8"
14,경북,NaN,NaN,NaN,"2,919.8","3,317.4","3,494.7","3,217.6","3,192.2","3,431.2",...,"5,926.2","7,792.9","8,567.6","8,473.6","8,244.3","8,675.7","8,815.2","8,590.2","9,181.6","10,350.8"
15,경남,NaN,NaN,NaN,"7,317.9","7,667.0","7,621.8","7,150.9","7,315.3","8,682.1",...,"14,727.8","16,344.2","18,507.4","18,785.0","19,432.7","19,548.1","19,654.3","20,619.0","22,262.8","23,271.2"
16,제주,NaN,NaN,NaN,747.5,625.4,547.7,543.6,580.4,682.3,...,"1,190.1","1,832.1","2,581.1","2,879.1","3,105.8","3,375.5","3,429.7","3,657.9","3,873.2","4,031.3"
17,세종,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,317.7","2,984.1","3,920.5","4,291.9","4,693.8","4,986.4","5,101.1","5,146.8","5,336.4","5,680.5"

In [156]:
debt_final.columns

Index(['지역코드', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023'],
      dtype='object')

In [162]:
import pandas as pd

df = pd.DataFrame(debt_final)

df.iloc[:, 1:] = df.iloc[:, 1:].apply(lambda x: x.str.replace(',', '').astype(float))

# 변환된 데이터프레임 확인
print(df)

   지역코드 2003년 2004년 2005년     2006년     2007년     2008년     2009년     2010년  \
0    전국   NaN   NaN   NaN  240951.4  245763.5  254735.7  273687.0  289623.0
1    서울   NaN   NaN   NaN  100226.7   98375.1  100188.8  104954.8  109489.9
2    부산   NaN   NaN   NaN   14475.1   14467.5   14525.9   15000.1   16333.4
3    대구   NaN   NaN   NaN    9160.8    9349.3    8847.3    8705.6    8450.9
4    인천   NaN   NaN   NaN   13963.4   15121.5   16134.6   19243.9   22601.9
5    광주   NaN   NaN   NaN    3440.2    3693.0    3997.8    3846.2    3987.2
6    대전   NaN   NaN   NaN    5491.7    5047.9    4930.0    5301.1    5942.9
7    울산   NaN   NaN   NaN    3268.4    3660.1    3942.1    3960.9    3731.7
8    경기   NaN   NaN   NaN   65012.5   69155.9   74606.6   85288.6   91020.6
9    강원   NaN   NaN   NaN    2849.6    2744.4    2557.8    2353.9    2386.4
10   충북   NaN   NaN   NaN    2841.3    3080.6    3298.4    3463.4    3441.4
11   충남   NaN   NaN   NaN    5004.7    5089.2    5830.5    6416.1    6567.2
12   전북   NaN   NaN   NaN    2670.7    2761.5    2780.8    2805.9    3037.2
13   전남   NaN   NaN   NaN    1561.0    1607.6    1430.8    1434.3    1544.4
14   경북   NaN   NaN   NaN    2919.8    3317.4    3494.7    3217.6    3192.2
15   경남   NaN   NaN   NaN    7317.9    7667.0    7621.8    7150.9    7315.3
16   제주   NaN   NaN   NaN     747.5     625.4     547.7     543.6     580.4
17   세종   NaN   NaN   NaN       NaN       NaN       NaN       NaN       NaN

       2011년  ...     2014년     2015년     2016년     2017년     2018년     2019년  \
0   308876.5  ...  365579.6  401728.5  442564.1  464208.5  494265.4  533966.4
1   113511.0  ...  123839.5  136921.7  150524.8  157613.3  166251.4  178277.8
2    18469.5  ...   24520.5   27491.0   30626.3   33439.5   36692.8   39787.6
3     8879.6  ...   13785.1   17589.8   18865.8   18603.1   19833.2   22240.0
4    25396.5  ...   26817.6   26988.8   29763.7   31800.6   33572.3   36794.2
5     4657.2  ...    6632.5    7828.7    8559.4    8584.3    9995.1   11720.9
6     7139.1  ...    9012.3    9255.6    9853.2   10267.7   10641.3   11611.5
7     4053.5  ...    6206.8    7032.0    7728.0    8312.9    8161.5    8113.7
8    95453.7  ...  104932.0  111369.0  123417.0  131152.8  142138.3  155050.5
9     2544.9  ...    3450.5    3530.9    3798.5    4310.7    5047.4    5755.5
10    3679.4  ...    5084.4    5756.7    5962.8    5973.9    6358.7    6611.4
11    6887.4  ...    8831.0   10338.3   10765.8   10081.6    9901.5    9887.4
12    3496.4  ...    5122.6    5321.7    5569.8    5931.0    6073.3    6488.8
13    1912.7  ...    3183.1    3350.9    3552.4    3707.5    4122.0    5041.3
14    3431.2  ...    5926.2    7792.9    8567.6    8473.6    8244.3    8675.7
15    8682.1  ...   14727.8   16344.2   18507.4   18785.0   19432.7   19548.1
16     682.3  ...    1190.1    1832.1    2581.1    2879.1    3105.8    3375.5
17       NaN  ...    2317.7    2984.1    3920.5    4291.9    4693.8    4986.4

       2020년     2021년     2022년     2023년
0   583896.8  629561.9  644132.4  672110.2
1   199946.5  223481.8  228104.3  237253.5
2    44409.9   47639.6   48559.5   50165.9
3    24998.6   28069.8   30169.0   32404.5
4    39234.0   42378.3   44104.5   46439.6
5    13304.1   14511.6   14049.1   14619.8
6    12841.7   13380.7   13265.0   14062.2
7     8273.7    8733.4    8911.5    9401.5
8   168418.9  176317.0  177453.1  183275.5
9     5941.2    6182.9    6727.2    7288.3
10    6492.7    6783.8    7017.6    7781.1
11   10237.5   11090.6   11974.7   12949.2
12    6758.5    6683.6    6846.4    6883.4
13    6039.1    6294.9    6296.4    6251.8
14    8815.2    8590.2    9181.6   10350.8
15   19654.3   20619.0   22262.8   23271.2
16    3429.7    3657.9    3873.2    4031.3
17    5101.1    5146.8    5336.4    5680.5

[18 rows x 22 columns]

In [165]:
debt_final.fillna(0)

/tmp/ipykernel_17812/3779502077.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  debt_final.fillna(0)

,지역코드,2003년,2004년,2005년,2006년,2007년,2008년,2009년,2010년,2011년,...,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년
0,전국,0,0,0,240951.4,245763.5,254735.7,273687.0,289623.0,308876.5,...,365579.6,401728.5,442564.1,464208.5,494265.4,533966.4,583896.8,629561.9,644132.4,672110.2
1,서울,0,0,0,100226.7,98375.1,100188.8,104954.8,109489.9,113511.0,...,123839.5,136921.7,150524.8,157613.3,166251.4,178277.8,199946.5,223481.8,228104.3,237253.5
2,부산,0,0,0,14475.1,14467.5,14525.9,15000.1,16333.4,18469.5,...,24520.5,27491.0,30626.3,33439.5,36692.8,39787.6,44409.9,47639.6,48559.5,50165.9
3,대구,0,0,0,9160.8,9349.3,8847.3,8705.6,8450.9,8879.6,...,13785.1,17589.8,18865.8,18603.1,19833.2,22240.0,24998.6,28069.8,30169.0,32404.5
4,인천,0,0,0,13963.4,15121.5,16134.6,19243.9,22601.9,25396.5,...,26817.6,26988.8,29763.7,31800.6,33572.3,36794.2,39234.0,42378.3,44104.5,46439.6
5,광주,0,0,0,3440.2,3693.0,3997.8,3846.2,3987.2,4657.2,...,6632.5,7828.7,8559.4,8584.3,9995.1,11720.9,13304.1,14511.6,14049.1,14619.8
6,대전,0,0,0,5491.7,5047.9,4930.0,5301.1,5942.9,7139.1,...,9012.3,9255.6,9853.2,10267.7,10641.3,11611.5,12841.7,13380.7,13265.0,14062.2
7,울산,0,0,0,3268.4,3660.1,3942.1,3960.9,3731.7,4053.5,...,6206.8,7032.0,7728.0,8312.9,8161.5,8113.7,8273.7,8733.4,8911.5,9401.5
8,경기,0,0,0,65012.5,69155.9,74606.6,85288.6,91020.6,95453.7,...,104932.0,111369.0,123417.0,131152.8,142138.3,155050.5,168418.9,176317.0,177453.1,183275.5
9,강원,0,0,0,2849.6,2744.4,2557.8,2353.9,2386.4,2544.9,...,3450.5,3530.9,3798.5,4310.7,5047.4,5755.5,5941.2,6182.9,6727.2,7288.3
10,충북,0,0,0,2841.3,3080.6,3298.4,3463.4,3441.4,3679.4,...,5084.4,5756.7,5962.8,5973.9,6358.7,6611.4,6492.7,6783.8,7017.6,7781.1
11,충남,0,0,0,5004.7,5089.2,5830.5,6416.1,6567.2,6887.4,...,8831.0,10338.3,10765.8,10081.6,9901.5,9887.4,10237.5,11090.6,11974.7,12949.2
12,전북,0,0,0,2670.7,2761.5,2780.8,2805.9,3037.2,3496.4,...,5122.6,5321.7,5569.8,5931.0,6073.3,6488.8,6758.5,6683.6,6846.4,6883.4
13,전남,0,0,0,1561.0,1607.6,1430.8,1434.3,1544.4,1912.7,...,3183.1,3350.9,3552.4,3707.5,4122.0,5041.3,6039.1,6294.9,6296.4,6251.8
14,경북,0,0,0,2919.8,3317.4,3494.7,3217.6,3192.2,3431.2,...,5926.2,7792.9,8567.6,8473.6,8244.3,8675.7,8815.2,8590.2,9181.6,10350.8
15,경남,0,0,0,7317.9,7667.0,7621.8,7150.9,7315.3,8682.1,...,14727.8,16344.2,18507.4,18785.0,19432.7,19548.1,19654.3,20619.0,22262.8,23271.2
16,제주,0,0,0,747.5,625.4,547.7,543.6,580.4,682.3,...,1190.1,1832.1,2581.1,2879.1,3105.8,3375.5,3429.7,3657.9,3873.2,4031.3
17,세종,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,2317.7,2984.1,3920.5,4291.9,4693.8,4986.4,5101.1,5146.8,5336.4,5680.5

In [168]:
debt_final = df.drop(['2003년', '2004년','2005년'], axis =1)

In [199]:
debt_final

,지역코드,2006년,2007년,2008년,2009년,2010년,2011년,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년
0,전국,240951.4,245763.5,254735.7,273687.0,289623.0,308876.5,318226.7,328923.1,365579.6,401728.5,442564.1,464208.5,494265.4,533966.4,583896.8,629561.9,644132.4,672110.2
1,서울,100226.7,98375.1,100188.8,104954.8,109489.9,113511.0,112091.6,113314.0,123839.5,136921.7,150524.8,157613.3,166251.4,178277.8,199946.5,223481.8,228104.3,237253.5
2,부산,14475.1,14467.5,14525.9,15000.1,16333.4,18469.5,20319.7,21832.2,24520.5,27491.0,30626.3,33439.5,36692.8,39787.6,44409.9,47639.6,48559.5,50165.9
3,대구,9160.8,9349.3,8847.3,8705.6,8450.9,8879.6,9863.2,10891.3,13785.1,17589.8,18865.8,18603.1,19833.2,22240.0,24998.6,28069.8,30169.0,32404.5
4,인천,13963.4,15121.5,16134.6,19243.9,22601.9,25396.5,25889.3,25387.2,26817.6,26988.8,29763.7,31800.6,33572.3,36794.2,39234.0,42378.3,44104.5,46439.6
5,광주,3440.2,3693.0,3997.8,3846.2,3987.2,4657.2,5325.4,6142.6,6632.5,7828.7,8559.4,8584.3,9995.1,11720.9,13304.1,14511.6,14049.1,14619.8
6,대전,5491.7,5047.9,4930.0,5301.1,5942.9,7139.1,7690.9,8441.2,9012.3,9255.6,9853.2,10267.7,10641.3,11611.5,12841.7,13380.7,13265.0,14062.2
7,울산,3268.4,3660.1,3942.1,3960.9,3731.7,4053.5,4668.3,5170.4,6206.8,7032.0,7728.0,8312.9,8161.5,8113.7,8273.7,8733.4,8911.5,9401.5
8,경기,65012.5,69155.9,74606.6,85288.6,91020.6,95453.7,96202.6,96216.9,104932.0,111369.0,123417.0,131152.8,142138.3,155050.5,168418.9,176317.0,177453.1,183275.5
9,강원,2849.6,2744.4,2557.8,2353.9,2386.4,2544.9,2869.7,3262.6,3450.5,3530.9,3798.5,4310.7,5047.4,5755.5,5941.2,6182.9,6727.2,7288.3
10,충북,2841.3,3080.6,3298.4,3463.4,3441.4,3679.4,3943.6,4204.6,5084.4,5756.7,5962.8,5973.9,6358.7,6611.4,6492.7,6783.8,7017.6,7781.1
11,충남,5004.7,5089.2,5830.5,6416.1,6567.2,6887.4,6769.5,7188.7,8831.0,10338.3,10765.8,10081.6,9901.5,9887.4,10237.5,11090.6,11974.7,12949.2
12,전북,2670.7,2761.5,2780.8,2805.9,3037.2,3496.4,4035.3,4678.6,5122.6,5321.7,5569.8,5931.0,6073.3,6488.8,6758.5,6683.6,6846.4,6883.4
13,전남,1561.0,1607.6,1430.8,1434.3,1544.4,1912.7,2432.2,2831.5,3183.1,3350.9,3552.4,3707.5,4122.0,5041.3,6039.1,6294.9,6296.4,6251.8
14,경북,2919.8,3317.4,3494.7,3217.6,3192.2,3431.2,3713.5,4359.3,5926.2,7792.9,8567.6,8473.6,8244.3,8675.7,8815.2,8590.2,9181.6,10350.8
15,경남,7317.9,7667.0,7621.8,7150.9,7315.3,8682.1,10757.3,12524.3,14727.8,16344.2,18507.4,18785.0,19432.7,19548.1,19654.3,20619.0,22262.8,23271.2
16,제주,747.5,625.4,547.7,543.6,580.4,682.3,793.2,962.7,1190.1,1832.1,2581.1,2879.1,3105.8,3375.5,3429.7,3657.9,3873.2,4031.3
17,세종,0.0,0.0,0.0,0.0,0.0,0.0,861.4,1515.0,2317.7,2984.1,3920.5,4291.9,4693.8,4986.4,5101.1,5146.8,5336.4,5680.5

In [ ]:

import mysql.connector

def connect_database(host_name="host_name", user_name="user_name", user_password="user_password"):
    mydb = mysql.connector.connect(
        host = host_name,
        port = 3306,
        user = user_name,
        password = user_password,
        database = "WAY_BACK_HOME"
    )
    cursor = mydb.cursor()
    return mydb, cursor
def close_database(mydb, cursor):
    cursor.close()
    mydb.close()
# 
def excute_query(query):
    mydb, cursor = connect_database()
    try:
        cursor.execute(query);
        if query.strip().lower().startswith("select"):
            return cursor.fetchall()
        else :
            mydb.commit()
            print("success!!!")
    except mysql.connector.Error as err:
        print(err)
    finally:
        close_database(mydb=mydb,cursor=cursor)


# excute_query("DROP TABLE debt")
excute_query('create TABLE debt (area varchar(50), 2006년 float, 2007년 float, 2008년 float, 2009년 float, 2010년 float, 2011년 float, 2012년 float, 2013년 float, 2014년 float, 2015년 float, 2016년 float, 2017년 float, 2018년 float, 2019년 float, 2020년 float, 2021년 float, 2022년 float, 2023년 float)')

success!!!

In [198]:
debt_final = debt_final.fillna(0)

/tmp/ipykernel_17812/2123529256.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  debt_final = debt_final.fillna(0)

In [ ]:
import mysql.connector
import pandas as pd

def connect_database(host_name="host_name", user_name="user_name", user_password="user_password"):
    mydb = mysql.connector.connect(
        host=host_name,
        port=3306,
        user=user_name,
        password=user_password,
        database="WAY_BACK_HOME"
    )
    cursor = mydb.cursor()
    return mydb, cursor

def close_database(mydb, cursor):
    cursor.close()
    mydb.close()

def excute_query(query, params=None):
    mydb, cursor = connect_database()
    try:
        if params:
            cursor.execute(query, params)  
        else:
            cursor.execute(query)
        if query.strip().lower().startswith("select"):
            return cursor.fetchall()
        else:
            mydb.commit()
            print("success!!!")
    except mysql.connector.Error as err:
        print(f"Error: {err}")
    finally:
        close_database(mydb=mydb, cursor=cursor)

debt_final = pd.DataFrame(debt_final)


def insert_data():
    for i, row in debt_final.iterrows():
        query = """
            INSERT INTO debt (area, 2006년, 2007년, 2008년, 2009년, 2010년, 2011년, 2012년, 2013년, 2014년, 2015년, 2016년, 2017년, 2018년, 2019년, 2020년, 2021년, 2022년, 2023년)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
        params = (
            row['지역코드'], row['2006년'], row['2007년'], row['2008년'], row['2009년'], row['2010년'],
            row['2011년'], row['2012년'], row['2013년'], row['2014년'], row['2015년'], row['2016년'],
            row['2017년'], row['2018년'], row['2019년'], row['2020년'], row['2021년'], row['2022년'], row['2023년']
        )
        excute_query(query, params)

insert_data()

success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!
success!!!